export const TOGGLE_AUTH_MODAL = 'TOGGLE_AUTH_MODAL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_TASKS_START = 'FETCH_ORDERS_START';
export const FETCH_TASKS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_TASKS_FAIL = 'FETCH_ORDERS_FAIL';

